module.exports = [
  { name: 'button', exports: [] },
  { name: 'checkbox', exports: [] },
  { name: 'checkbox-group', exports: [] },
  { name: 'form', exports: [] },
  { name: 'fieldset', exports: [] },
  { name: 'icon', exports: [] },
  { name: 'input', exports: [] },
  { name: 'input-amount', exports: ['formatAmount', 'parseAmount'] },
  { name: 'input-date', exports: [] },
  { name: 'input-email', exports: [] },
  { name: 'input-iban', exports: ['formatIBAN', 'parseIBAN', 'isCountryIBAN', 'isCountryIBANValidator', 'isIBAN', 'isIBANValidator'] },
  { name: 'radio', exports: [] },
  { name: 'radio-group', exports: [] },
  { name: 'select', exports: [] },
  { name: 'steps', exports: [] },
  { name: 'textarea', exports: [] },
];